### ISSUE TITLE
Can´t create a project, get stuck on "choose a team"!

### ISSUE THREAD

**Issue by eduardosanzb** [icescrum/iceScrum#27]
Hello! 
I already deploy icesscrum on a Ubuntu Virtual Server, after all the configuration, I just realised that I cannot create a project from scratch, when I´m in the second step "Choose a team", I select my already created team, but nothing happen..
Any thought ???
Kind Regards!

P.D. a quick solution I found is create a project with the cloud free account in icescrum, export it and then import it to my server. But I think is not the best solution.

********NANO FROM icescrum.log

2015-07-20 04:16:59,897 [pool-2-thread-1] INFO  grails.spring.BeanBuilder  - [RuntimeConfiguration] Configuring data source for environment: PRODUCTION
2015-07-20 04:17:03,724 [pool-2-thread-1] WARN  grails.util.GrailsUtil  - [WARNING] Property [data] of domain class pl.burningice.plugins.image.ast.Image has type [[B] and doesn't support constraint [blank]. This constraint will not be checked during validation.
2015-07-20 04:17:04,097 [pool-2-thread-1] WARN  net.sf.ehcache.config.ConfigurationFactory  - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/var/lib/tomcat7/webapps/icescrum/WEB-INF/lib/ehcache-core-1.7.1.jar!/ehc$
2015-07-20 04:17:06,760 [pool-2-thread-1] WARN  net.sf.ehcache.config.ConfigurationFactory  - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/var/lib/tomcat7/webapps/icescrum/WEB-INF/lib/ehcache-core-1.7.1.jar!/ehc$
2015-07-20 04:17:06,768 [pool-2-thread-1] WARN  net.sf.ehcache.CacheManager  - Creating a new instance of CacheManager using the diskStorePath "/tmp/tomcat7-tomcat7-tmp" which is already used by an existing CacheManager.
The source of the configuration was classpath.
The diskStore path for this CacheManager will be set to /tmp/tomcat7-tomcat7-tmp/ehcache_auto_created_1437383826768.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.
2015-07-20 04:17:07,915 [pool-2-thread-1] WARN  net.sf.ehcache.config.ConfigurationFactory  - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/var/lib/tomcat7/webapps/icescrum/WEB-INF/lib/ehcache-core-1.7.1.jar!/ehc$
2015-07-20 04:17:07,919 [pool-2-thread-1] WARN  net.sf.ehcache.CacheManager  - Creating a new instance of CacheManager using the diskStorePath "/tmp/tomcat7-tomcat7-tmp" which is already used by an existing CacheManager.
The source of the configuration was classpath.
The diskStore path for this CacheManager will be set to /tmp/tomcat7-tomcat7-tmp/ehcache_auto_created_1437383827919.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.
2015-07-20 04:17:09,398 [pool-2-thread-1] INFO  org.codehaus.groovy.grails.scaffolding.DefaultGrailsTemplateGenerator  - Scaffolding template generator set to use resource loader org.codehaus.groovy.grails.commons.spring.GrailsWebApplicationContext@3520982f: startup date$
2015-07-20 04:17:18,208 [pool-2-thread-1] ERROR org.hibernate.util.JDBCExceptionReporter  - Unknown column 'text_as' in 'field list'
2015-07-20 04:17:19,051 [pool-2-thread-1] INFO  AutobaseGrailsPlugin  - ---- Starting Autobase migrations  ----
2015-07-20 04:17:19,296 [pool-2-thread-1] INFO  liquibase.ext.logging.LiquibaseSlf4jLogger  - Successfully acquired change log lock
2015-07-20 04:17:20,420 [pool-2-thread-1] INFO  liquibase.ext.logging.LiquibaseSlf4jLogger  - Reading from `DATABASECHANGELOG`
2015-07-20 04:17:20,725 [pool-2-thread-1] WARN  liquibase.ext.logging.LiquibaseSlf4jLogger  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2015-07-20 04:17:20,772 [pool-2-thread-1] INFO  liquibase.ext.logging.LiquibaseSlf4jLogger  - Successfully released change log lock
2015-07-20 04:17:20,775 [pool-2-thread-1] INFO  AutobaseGrailsPlugin  - ---- Autobase migrations completed ----
2015-07-20 04:17:23,759 [pool-2-thread-1] WARN  grails.util.GrailsUtil  - [WARNING] Property [data] of domain class pl.burningice.plugins.image.ast.Image has type [[B] and doesn't support constraint [blank]. This constraint will not be checked during validation.
2015-07-20 04:17:23,771 [pool-2-thread-1] INFO  org.codehaus.groovy.grails.web.context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
2015-07-20 04:17:23,945 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Installing BroadcastFilter class(es) org.atmosphere.client.TrackMessageSizeFilter
2015-07-20 04:17:23,967 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Installed AtmosphereHandler org.icescrum.atmosphere.IceScrumAtmosphereHandler@52e75003 mapped to context-path: /stream/app/*
2015-07-20 04:17:24,020 [pool-2-thread-1] INFO  org.atmosphere.cpr.DefaultBroadcaster  - /stream/app/* support Out Of Order Broadcast: false
2015-07-20 04:17:24,027 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Auto detecting WebSocketHandler in /WEB-INF/classes/
2015-07-20 04:17:27,400 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
2015-07-20 04:17:27,404 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: Apache Tomcat/7.0.26 using javax.servlet/3.0
2015-07-20 04:17:27,405 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Installed AtmosphereInterceptor Browser disconnection detection.
2015-07-20 04:17:27,406 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol.
2015-07-20 04:17:27,406 [pool-2-thread-1] WARN  org.atmosphere.cpr.AtmosphereFramework  - No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
2015-07-20 04:17:27,406 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Using BroadcastFilter: org.atmosphere.client.TrackMessageSizeFilter
2015-07-20 04:17:27,406 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Shared ExecutorService supported: true
2015-07-20 04:17:27,407 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - HttpSession supported: false
2015-07-20 04:17:27,407 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
2015-07-20 04:17:27,407 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
2015-07-20 04:17:27,407 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Using Broadcaster: org.icescrum.atmosphere.IceScrumBroadcaster
2015-07-20 04:17:27,408 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  - Atmosphere Framework 1.0.15 started.
2015-07-20 04:17:27,408 [pool-2-thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework  -

        For Atmosphere Framework Commercial Support, visit
        http://www.async-io.org/ or send an email to support@async-io.org

2015-07-20 04:17:27,788 [Thread-7] INFO  org.atmosphere.cpr.AtmosphereFramework  -

        Current version of Atmosphere 1.0.15
        Newest version of Atmosphere available 2.0.10

//*********     ******////

******NANO FROM STACKTRACE.LOG.1

2015-07-20 03:16:57,213 [pool-2-thread-1] ERROR StackTrace  - Sanitizing stacktrace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageSource': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot $
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
        at org.codehaus.groovy.grails.commons.spring.ReloadAwareAutowireCapableBeanFactory.doCreateBean(ReloadAwareAutowireCapableBeanFactory.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.context.support.AbstractApplicationContext.initMessageSource(AbstractApplicationContext.java:755)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:413)
        at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:154)
        at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:164)
        at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:124)
        at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:120)
        at org.codehaus.groovy.grails.web.context.GrailsContextLoader.createWebApplicationContext(GrailsContextLoader.java:73)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4779)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1617)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.B$
        ... 6 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'lobHandlerDetector' while setting bean property 'lobHandler'; nested exception is org.springframework.beans.factory.BeanC$
        ... 6 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lobHandlerDetector': Invocation of init method failed; nested exception is org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData$
        ... 6 more
Caused by: org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 t$
        ... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2237)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2158)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
        at com.sun.proxy.$Proxy18.getMetaData(Unknown Source)
        ... 6 more
Caused by: java.sql.SQLException: Access denied for user 'icescrum'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:943)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4113)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1308)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2336)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2176)
        ... 13 more

**Comment by vbarrier** [comment]
Hello Edouard, 

iceScrum can't connect to the SQL server this is why you can't create a project / team or doing anythingg that save to the database.

```javascript
Caused by: java.sql.SQLException: Access denied for user 'icescrum'@'localhost' (using password: YES)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)

**Comment by eduardosanzb** [comment]
Hello!! Thank u for ur super quick reply! Well I just check my database and I see that I forgot to grant the privileges. Now I did it.

```
select host, user, insert_priv, update_priv from mysql.user;
+-----------+------------------+-------------+-------------+
| host      | user             | insert_priv | update_priv |
+-----------+------------------+-------------+-------------+
| localhost | root             | Y           | Y           |
| scrum     | root             | Y           | Y           |
| 127.0.0.1 | root             | Y           | Y           |
| ::1       | root             | Y           | Y           |
| localhost | debian-sys-maint | Y           | Y           |
| localhost | icescrum         | Y           | Y           |
| localhost | newuser          | Y           | Y           |
+-----------+------------------+-------------+-------------+
7 rows in set (0.00 sec)

```
But I still have not the access

![screen shot 2015-07-20 at 4 48 15 am](https://cloud.githubusercontent.com/assets/4089986/8773538/9caad182-2e9a-11e5-897f-e867927e059f.png)

**Comment by eduardosanzb** [comment]
icescrum.properties
```
#Data Source

dataSource.driverClassName=com.mysql.jdbc.Driver

dataSource.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

dataSource.url=jdbc:mysql://localhost:3306/icescrum?useUnicode=true&characterEncoding=utf8&autoReconnect=true

dataSource.username=icescrum

dataSource.password=pass

dataSource.dbCreate=update

#Use pool connection

dataSource.pooled=true

dataSource.properties.maxActive = 50

dataSource.properties.maxIdle = 25

dataSource.properties.minIdle = 1

dataSource.properties.initialSize = 1

dataSource.properties.minEvictableIdleTimeMillis = 1800000

dataSource.properties.timeBetweenEvictionRunsMillis = 1800000

dataSource.properties.numTestsPerEvictionRun = 3

dataSource.properties.maxWait = 10000

dataSource.properties.testOnBorrow = true

dataSource.properties.testWhileIdle = true
dataSource.properties.testOnReturn = false

dataSource.properties.validationQuery = "SELECT 1"



#serverURL Absolute link required with context name like : http://localhost:8080/icescrum

grails.serverURL=http://localhost:8080/icescrum

```

**Comment by vbarrier** [comment]
Eduardo, you should take a look at our documentation ;) We don't use properties file since years! 
iceScrum use a config.groovy (note the groovy extension file). 

So your config.groovy file should be like that: 

```groovy
//Data Source
dataSource {
            pooled = true
            username = "icescrum"
            password = "pass"
            dialect = org.hibernate.dialect.MySQL5InnoDBDialect
            driverClassName = "com.mysql.jdbc.Driver"
            url = "jdbc:mysql://MYSQL_SERVER_URL/icescrum"
        }
//serverURL Absolute link required with context name like : http://localhost:8080/icescrum
grails.serverURL=http://169.57.10.253:8080/icescrum
```

Also you access iceScrum from an external ip 169.57.10.253 but you still have a serverURL with localhost in config so it can't work.

**Comment by vbarrier** [comment]
Documentation link : https://www.icescrum.com/documentation/install-guide ;)
