### ISSUE TITLE
error on submit local domain for email on setup

### ISSUE THREAD

**Issue by ZamanOof** [icescrum/iceScrum#38]
Hello,
i try to submit a details for local mail server but there is no luck,that show:
`Error, the connection failed, please check that your email server is available on this port and that you entered the proper Technical settings`
on container logs:
`	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.CrawlerSessionManagerValve.invoke(CrawlerSessionManagerValve.java:207)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: test.loc
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:301)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:229)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1950)
	... 121 more
`
show **Caused by: java.net.UnknownHostException: test.loc**
so what to do?
Best Regards

**Comment by noullet** [comment]
Hi,

As you see in the stacktrace, iceScrum is not really involved in this error, the state of the art Java SMTP libraries are used quite directly. Moreover, we never received any report regarding local email server hosts. This points to a configuration issue rather than an iceScrum bug. Thus, I close this issue. If you manage to establish that iceScrum is at fault, we will reopen the issue and investigate the case.

Support is normally limited to paying customers, but here is what we would look for in order to solve the issue: your host must be known to the user who starts iceScrum. You may check that the host file of this user includes your host, and maybe try calling the smtp server with `telnet`.

**Comment by ZamanOof** [comment]
> Hi,
> 
> As you see in the stacktrace, iceScrum is not really involved in this error, the state of the art Java SMTP libraries are used quite directly. Moreover, we never received any report regarding local email server hosts. This points to a configuration issue rather than an iceScrum bug. Thus, I close this issue. If you manage to establish that iceScrum is at fault, we will reopen the issue and investigate the case.
> 
> Support is normally limited to paying customers, but here is what we would look for in order to solve the issue: your host must be known to the user who starts iceScrum. You may check that the host file of this user includes your host, and maybe try calling the smtp server with `telnet`.

Thanks For Reply,
**First:** I'm at installation stage at Emails page.
get the mentions error.
`Error, the connection failed, please check that your email server is available on this port and that you entered the proper Technical settings`
**Second:** actually I'm connected to it and works without a problem using client email.
**Third**: the mail host accessible from container after check.
and look like the logs of container is **catalina.out** 
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
javax.mail.MessagingException: Could not connect to SMTP host: test.loc, port: 465, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:656)
	at javax.mail.Service.connect(Service.java:345)
	at javax.mail.Service$connect$1.call(Unknown Source)

and the port is opend:
```
nmap test.loc -p465
Nmap scan report for test.loc (xxxxxxxx)
Host is up (0.00085s latency).
PORT    STATE SERVICE
465/tcp open  smtps
Nmap done: 1 IP address (1 host up) scanned in 0.55 seconds
```
I was able to connect to the server from thunderbird
as 
**port:465 SSL/TLS Normal Password**
Note: I'm using self signed certificate with added CA
Best Regards

**Comment by noullet** [comment]
Hi, thanks for the details. It looks like you solved the first issue as the error message is different now. 

Did you configure the "technical settings" as explained in our documentation? https://www.icescrum.com/documentation/how-to-install-icescrum/

The self signed certificate may also be at fault. In such case, you will have to register it on a keystore provided to java.

**Comment by ZamanOof** [comment]
I had to add a certificate to Java not to a system as u said by 
**getting certificate:**
`echo -n | openssl s_client -connect test.loc:465 |    sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./examplecert.crt
`
To get a .cert from server.
and **adding it to openJDK8** 
`keytool -importcert -file examplecert.crt  -alias test -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit
`
but after finishing the settings a get 
`error invalid email`
when change it to public domain name for email of Administrator user and was the response from server as 400 with the message.
Best regards

**Comment by noullet** [comment]
Thank you for providing the commands you use, this may be useful for other users!

Regarding the administrator account email, can you temporarily use another email address?

**Comment by noullet** [comment]
Regarding your latest issue, we have found its origin and it will be fixed in our next version.

In the meantime, as a workaround you can enter an email address with a regular tld (such as .com .org .net...) in the wizard, and then you can change it from the administration account later on.

**Comment by noullet** [comment]
Hi, local administrator email addresses are now accepted in iceScrum 7.44, see https://www.icescrum.com/blog/icescrum-v7-44/
