### ISSUE TITLE
Can't install using postgresql 12

### ISSUE THREAD

**Issue by lonix1** [icescrum/iceScrum#43]
I'm using the `latest` icescrum image, with the `12.2` postgresql image.

Steps:
- I followed the instructions to create `docker-compose.yml`
- I started with `docker-compose up`
- I know I'm using the correct postgres username, password and server name, because if I don't then the install stops immediately with an error
- Once ready, I completed the installation wizard
- I restarted with `docker restart icescrum`
- The installation failed, see log below

> ...other stuff
icescrum_1    | Configuring Spring Security OAuth2 provider ...
icescrum_1    | ... done configuring Spring Security OAuth2 provider
postgresql_1  | 2020-05-08 04:07:42.783 UTC [41] ERROR:  constraint "uk_iy7ua5fso3il3u3ymoc4uf35w" of relation "acl_class" does not exist
postgresql_1  | 2020-05-08 04:07:42.783 UTC [41] STATEMENT:  alter table acl_class drop constraint UK_iy7ua5fso3il3u3ymoc4uf35w
postgresql_1  | 2020-05-08 04:07:42.789 UTC [41] ERROR:  constraint "unique_ace_order" of relation "acl_entry" does not exist
postgresql_1  | 2020-05-08 04:07:42.789 UTC [41] STATEMENT:  alter table acl_entry drop constraint unique_ace_order
postgresql_1  | 2020-05-08 04:07:42.792 UTC [41] ERROR:  constraint "unique_object_id_identity" of relation "acl_object_identity" does not exist
postgresql_1  | 2020-05-08 04:07:42.792 UTC [41] STATEMENT:  alter table acl_object_identity drop constraint unique_object_id_identity
postgresql_1  | 2020-05-08 04:07:42.796 UTC [41] ERROR:  constraint "unique_principal" of relation "acl_sid" does not exist
postgresql_1  | 2020-05-08 04:07:42.796 UTC [41] STATEMENT:  alter table acl_sid drop constraint unique_principal
postgresql_1  | 2020-05-08 04:07:42.800 UTC [41] ERROR:  constraint "uk_nrgoi6sdvipfsloa7ykxwlslf" of relation "authority" does not exist
postgresql_1  | 2020-05-08 04:07:42.800 UTC [41] STATEMENT:  alter table authority drop constraint UK_nrgoi6sdvipfsloa7ykxwlslf
postgresql_1  | 2020-05-08 04:07:42.814 UTC [41] ERROR:  constraint "unique_nameisactor" of relation "is_actor" does not exist
postgresql_1  | 2020-05-08 04:07:42.814 UTC [41] STATEMENT:  alter table is_actor drop constraint unique_nameisactor
postgresql_1  | 2020-05-08 04:07:42.821 UTC [41] ERROR:  constraint "unique_code" of relation "is_backlog" does not exist
postgresql_1  | 2020-05-08 04:07:42.821 UTC [41] STATEMENT:  alter table is_backlog drop constraint unique_code
postgresql_1  | 2020-05-08 04:07:42.826 UTC [41] ERROR:  constraint "unique_nameisbugtracker" of relation "is_bugtracker" does not exist
postgresql_1  | 2020-05-08 04:07:42.826 UTC [41] STATEMENT:  alter table is_bugtracker drop constraint unique_nameisbugtracker
postgresql_1  | 2020-05-08 04:07:42.833 UTC [41] ERROR:  constraint "unique_nameisbugtrackerimport" of relation "is_bugtracker_import" does not exist
postgresql_1  | 2020-05-08 04:07:42.833 UTC [41] STATEMENT:  alter table is_bugtracker_import drop constraint unique_nameisbugtrackerimport
postgresql_1  | 2020-05-08 04:07:42.838 UTC [41] ERROR:  constraint "unique_on_state" of relation "is_bugtracker_sync" does not exist
postgresql_1  | 2020-05-08 04:07:42.838 UTC [41] STATEMENT:  alter table is_bugtracker_sync drop constraint unique_on_state
postgresql_1  | 2020-05-08 04:07:42.845 UTC [41] ERROR:  constraint "unique_nameisfeature" of relation "is_feature" does not exist
postgresql_1  | 2020-05-08 04:07:42.845 UTC [41] STATEMENT:  alter table is_feature drop constraint unique_nameisfeature
postgresql_1  | 2020-05-08 04:07:42.865 UTC [41] ERROR:  constraint "unique_feeling_day" of relation "is_mood" does not exist
postgresql_1  | 2020-05-08 04:07:42.865 UTC [41] STATEMENT:  alter table is_mood drop constraint unique_feeling_day
postgresql_1  | 2020-05-08 04:07:42.869 UTC [41] ERROR:  constraint "uk_png96g0s5k1xbgpcpx9kjbpwy" of relation "is_oauth_a_token" does not exist
postgresql_1  | 2020-05-08 04:07:42.869 UTC [41] STATEMENT:  alter table is_oauth_a_token drop constraint UK_png96g0s5k1xbgpcpx9kjbpwy
postgresql_1  | 2020-05-08 04:07:42.873 UTC [41] ERROR:  constraint "uk_jufwrsv8q8d8oq5jfn8whgppt" of relation "is_oauth_a_token" does not exist
postgresql_1  | 2020-05-08 04:07:42.873 UTC [41] STATEMENT:  alter table is_oauth_a_token drop constraint UK_jufwrsv8q8d8oq5jfn8whgppt
postgresql_1  | 2020-05-08 04:07:42.879 UTC [41] ERROR:  constraint "uk_qn1cdae2qtyhdee2ohneytasy" of relation "is_oauth_auth_code" does not exist
postgresql_1  | 2020-05-08 04:07:42.879 UTC [41] STATEMENT:  alter table is_oauth_auth_code drop constraint UK_qn1cdae2qtyhdee2ohneytasy
postgresql_1  | 2020-05-08 04:07:42.885 UTC [41] ERROR:  constraint "uk_ntxba9iut1cag4tn46i9r4nme" of relation "is_oauth_client" does not exist
postgresql_1  | 2020-05-08 04:07:42.885 UTC [41] STATEMENT:  alter table is_oauth_client drop constraint UK_ntxba9iut1cag4tn46i9r4nme
postgresql_1  | 2020-05-08 04:07:42.894 UTC [41] ERROR:  constraint "uk_baaxi4c4cicc420frwnbq8536" of relation "is_oauth_r_token" does not exist
postgresql_1  | 2020-05-08 04:07:42.894 UTC [41] STATEMENT:  alter table is_oauth_r_token drop constraint UK_baaxi4c4cicc420frwnbq8536
postgresql_1  | 2020-05-08 04:07:42.902 UTC [41] ERROR:  constraint "uk_6gljpwex9hlvgwdmdwyuv4i2m" of relation "is_portfolio" does not exist
postgresql_1  | 2020-05-08 04:07:42.902 UTC [41] STATEMENT:  alter table is_portfolio drop constraint UK_6gljpwex9hlvgwdmdwyuv4i2m
postgresql_1  | 2020-05-08 04:07:42.909 UTC [41] ERROR:  constraint "uk_gcdvyw9ni607np6jjbsgibrdc" of relation "is_project" does not exist
postgresql_1  | 2020-05-08 04:07:42.909 UTC [41] STATEMENT:  alter table is_project drop constraint UK_gcdvyw9ni607np6jjbsgibrdc
postgresql_1  | 2020-05-08 04:07:42.926 UTC [41] ERROR:  constraint "unique_name" of relation "is_release" does not exist
postgresql_1  | 2020-05-08 04:07:42.926 UTC [41] STATEMENT:  alter table is_release drop constraint unique_name
postgresql_1  | 2020-05-08 04:07:42.937 UTC [41] ERROR:  constraint "unique_code" of relation "is_roadmap" does not exist
postgresql_1  | 2020-05-08 04:07:42.937 UTC [41] STATEMENT:  alter table is_roadmap drop constraint unique_code
postgresql_1  | 2020-05-08 04:07:42.940 UTC [41] ERROR:  relation "unique_code" already exists
postgresql_1  | 2020-05-08 04:07:42.940 UTC [41] STATEMENT:  alter table is_roadmap add constraint unique_code  unique (project_id, code)
postgresql_1  | 2020-05-08 04:07:42.953 UTC [41] ERROR:  constraint "unique_nameisstory" of relation "is_story" does not exist
postgresql_1  | 2020-05-08 04:07:42.953 UTC [41] STATEMENT:  alter table is_story drop constraint unique_nameisstory
postgresql_1  | 2020-05-08 04:07:42.959 UTC [41] ERROR:  constraint "unique_nameistbntpls" of relation "is_tbn_tpls" does not exist
postgresql_1  | 2020-05-08 04:07:42.959 UTC [41] STATEMENT:  alter table is_tbn_tpls drop constraint unique_nameistbntpls
postgresql_1  | 2020-05-08 04:07:42.971 UTC [41] ERROR:  constraint "uk_joplui1h2lxa8segeo32qe9vv" of relation "is_team" does not exist
postgresql_1  | 2020-05-08 04:07:42.971 UTC [41] STATEMENT:  alter table is_team drop constraint UK_joplui1h2lxa8segeo32qe9vv
postgresql_1  | 2020-05-08 04:07:42.979 UTC [41] ERROR:  constraint "unique_nameistemplate" of relation "is_template" does not exist
postgresql_1  | 2020-05-08 04:07:42.979 UTC [41] STATEMENT:  alter table is_template drop constraint unique_nameistemplate
postgresql_1  | 2020-05-08 04:07:42.996 UTC [41] ERROR:  constraint "uk_4df3sax6nqy447209fmms37m6" of relation "is_user" does not exist
postgresql_1  | 2020-05-08 04:07:42.996 UTC [41] STATEMENT:  alter table is_user drop constraint UK_4df3sax6nqy447209fmms37m6
postgresql_1  | 2020-05-08 04:07:43.001 UTC [41] ERROR:  constraint "uk_pf9tt1u18mb4ij95mvdxmqt5f" of relation "is_user" does not exist
postgresql_1  | 2020-05-08 04:07:43.001 UTC [41] STATEMENT:  alter table is_user drop constraint UK_pf9tt1u18mb4ij95mvdxmqt5f
postgresql_1  | 2020-05-08 04:08:06.314 UTC [41] ERROR:  column "adsrc" does not exist at character 205
postgresql_1  | 2020-05-08 04:08:06.314 UTC [41] STATEMENT:  SELECT relname AS SEQUENCE_NAME FROM pg_class, pg_namespace WHERE relkind='S' AND pg_class.relnamespace = pg_namespace.oid AND ns
pname = 'public' AND 'nextval('''||relname||'''::regclass)' not in (select adsrc from pg_attrdef where adsrc is not null) AND 'nextval(''"'||relname||'"''::regclass)' not in (select adsrc fr
om pg_attrdef where adsrc is not null) AND 'nextval('''||relname||'''::regclass)' not in (select adsrc from pg_attrdef where adsrc is not null)
icescrum_1    | ...--------------------------------------------------------
icescrum_1    | ERROR: iceScrum failed to start. Please read the logs above and icescrum.log in order to find the cause and fix it.
icescrum_1    | --------------------------------------------------------
icescrum_1    | --------------------------------------------------------
icescrum_1    | iceScrum is stopped
icescrum_1    | --------------------------------------------------------

My `docker-compose.yml`:
````yml
version: '3.7'

services:
  postgresql: 
    image: postgres:12.2
    volumes: 
      - postgresql:/var/lib/postgresql/data/ 
    environment: 
      POSTGRES_DB: icescrum 
      POSTGRES_USER: icescrum 
      POSTGRES_PASSWORD: icescrum 
    networks: 
      - icescrum 
  icescrum:
    image: icescrum/icescrum:latest
    volumes:
      - ./data/:/root/
    environment:
      POSTGRES_DB: icescrum 
      POSTGRES_PASSWORD: icescrum 
      ICESCRUM_CONTEXT: /
    ports:
      - '8000:8080'
    depends_on:
      - postgresql 
    networks:
      - icescrum

volumes:
  postgresql: 

networks:
  icescrum:
````

If I use mariadb, everything works perfectly.

Any idea what is my mistake?

**Comment by noullet** [comment]
Hi,

Apparently iceScrum does not work with PostgreSQL 12. Our documentation has been updated accordingly.

There is no easy fix or workaround so you will have to use an earlier version. Version 11 should work fine.

**Comment by lonix1** [comment]
That's a pity because as you know postgres uses much less memory even on a small server. (It's also faster in my experience.)

But I will use mariadb instead, at least it works... Thanks for your reply!

**Comment by noullet** [comment]
You can still use Postgres! 

It's only the latest version (12) that does not work with iceScrum, earlier versions work fine.

**Comment by noullet** [comment]
If you don't mind, I reopen the issue as it is a real one and keeping track of it may help other users!

**Comment by umutalacam** [comment]
It is still happening. 

```
igration failed for change set changelog-7-0-2.groovy::is_task-name-dropUniqueConstraint::noullet:
     Reason:
          changelog.groovy : ERROR: column "adsrc" does not exist
  Position: 205
:
          Caused By: Precondition Error
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-7-0-2.groovy::is_task-name-dropUniqueConstraint::noul
let:
     Reason:                                                                                                                                                      changelog.groovy : ERROR: column "adsrc" does not exist
  Position: 205
:                                                                                                                                                                 Caused By: Precondition Error
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:285)
```

Could it be resolved by upgrading the dependencies of the project? Postgresql is quite powerful for low-end hardware. And it is advertised that ice-scrum supports the postgresql.

If you can provide a pathforward I can try to fix it.
